lib/ci_metrics_web/router.ex
defmodule CiMetricsWeb.Router do
  use CiMetricsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CiMetricsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController, only: [:index, :show]
    resources "/repositories", RepositoryController, only: [:new, :create, :show]
  end

  scope "/api", CiMetricsWeb do
    pipe_through :api

    resources "/events", EventController, only: [:create]
  end
end

lib/amadeus_cho/organizations/repository.ex
defmodule AmadeusCho.Repository do
  use Ecto.Schema
  import Ecto.Changeset

  # This name is not confusing at all
  alias AmadeusCho.{Repository, Repo}

  schema "repositories" do
    field :name, :string
    field :owner, :string
    has_many :events, AmadeusCho.Event

    timestamps()
  end

  def get_by(params) do
    Repo.get_by(Repository, params)
  end

  def insert_or_update(params) do
    case Repo.get_by(Repository, params) do
      nil -> %Repository{}
      repository -> repository
    end
    |> changeset(params)
    |> Repo.insert_or_update()
  end

  def get_all do
    Repo.all(Repository)
  end

  @doc false
  def changeset(repository, attrs) do
    repository
    |> cast(attrs, [:name, :owner])
    |> validate_required([:name, :owner])
  end
end

lib/ci_metrics/project/repository.ex
defmodule CiMetrics.Project.Repository do
  use Ecto.Schema
  import Ecto.Changeset

  alias CiMetrics.Repo
  # This name is not confusing at all
  alias CiMetrics.Project.Repository

  schema "repositories" do
    field :name, :string
    field :owner, :string
    field :deployment_strategy, CiMetrics.AtomType
    has_many :events, CiMetrics.Events.Event
    has_many :commits, CiMetrics.Project.Commit
    has_many :deployments, CiMetrics.Events.Deployment

    timestamps()
  end

  def full_name(%{owner: owner, name: name}) do
    "#{owner}/#{name}"
  end

  def get(id) when is_binary(id) do
    id
    |> Integer.parse()
    |> Tuple.to_list()
    |> List.first()
    |> get()
  end

  def get(id) when is_integer(id) do
    Repo.get(Repository, id)
  end

  def get_by(params) do
    Repo.get_by(Repository, params)
  end

  def get_all do
    Repo.all(Repository)
  end

  def insert_or_update(params) do
    case Repo.get_by(Repository, params) do
      nil -> %Repository{}
      repository -> repository
    end
    |> changeset(params)
    |> Repo.insert_or_update()
  end

  def from_raw_event(raw_event) do
    raw_event
    |> extract_repository_info()
    |> Repository.insert_or_update()
  end

  def changeset(repository, attrs) do
    repository
    |> cast(attrs, [:name, :owner, :deployment_strategy])
    |> validate_required([:name, :owner])
    |> unique_constraint(:name, name: :repositories_name_owner_index)
  end

  defp extract_repository_info(raw_event) do
    repository_full_name = Kernel.get_in(raw_event, ["repository", "full_name"])
    git_url = Kernel.get_in(raw_event, ["repository", "git_url"])

    [owner, name] = parse_repository_name(repository_full_name, git_url)

    %{owner: owner, name: name}
  end

  defp parse_repository_name(nil, git_url) do
    git_url
    |> URI.parse()
    |> Map.get(:path)
    |> Path.rootname()
    |> Path.relative()
    |> Path.split()
  end

  defp parse_repository_name(repository_full_name, _) do
    String.split(repository_full_name, "/")
  end
end

lib/ci_metrics_web/controllers/repository_controller.ex
defmodule CiMetricsWeb.RepositoryController do
  require Logger
  use CiMetricsWeb, :controller
  alias CiMetrics.GithubProject
  alias CiMetrics.Metrics.TimeUnitMetric
  alias CiMetrics.Project.Repository

  @project Application.get_env(:ci_metrics, :project, GithubProject)

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{
        "repository_name" => repository_name,
        "access_token" => access_token,
        "deployment_strategy" => deployment_strategy
      }) do
    with {:ok, :webhook_created} <- GithubProject.create_webhook(repository_name, access_token),
         {:ok, _repository} <-
           GithubProject.create_repository(repository_name, deployment_strategy) do
      conn
      |> put_flash(:info, "Repository set up successfully.")
      |> render("new.html")
    else
      {:error, error} ->
        Logger.error(inspect(error))
        error_message = error_to_user_message(error)

        conn
        |> put_flash(:error, error_message)
        |> render("new.html")
    end
  end

  def show(conn, params) do
    lead_time =
      params["id"]
      |> @project.calculate_lead_time()
      |> TimeUnitMetric.to_string()

    lead_time_snapshots = @project.daily_lead_time_snapshots(params["id"])

    lead_times_in_days =
      lead_time_snapshots
      |> Enum.map(&TimeUnitMetric.new(&1.average_lead_time))
      |> Enum.map(&TimeUnitMetric.in_hours(&1))
      |> Enum.map(&Float.to_string(&1))

    lead_time_dates =
      lead_time_snapshots
      |> Enum.map(fn %{inserted_at: d} -> "#{d.month}/#{d.day}/#{d.year}" end)

    %{owner: owner, name: name} = Repository.get(params["id"])

    repo = %{
      owner: owner,
      name: name,
      average_lead_time: lead_time,
      dates: lead_time_dates,
      lead_times: lead_times_in_days
    }

    render(conn, "show.html", repository: repo)
  end

  defp error_to_user_message(:webhook_exists),
    do: "Oops! This repository already has a webhook from us."

  defp error_to_user_message(:repository_not_found), do: "Oops! We couldn't find that repository."

  defp error_to_user_message(:invalid_credentials),
    do: "Oops! The access token you provided doesn't seem to be working."

  defp error_to_user_message(:webhook_error),
    do: "Oops! We had some trouble creating a webhook for your repository. Please try again."

  defp error_to_user_message(_),
    do: "Oops! We had some trouble setting up your repository. Please try again."
end

lib/ci_metrics_web/views/repository_view.ex
defmodule CiMetricsWeb.RepositoryView do
  use CiMetricsWeb, :view

  def full_name(%{owner: owner, name: name}) do
    "#{owner}/#{name}"
  end

  def deployment_strategies do
    [
      [key: "Heroku", value: :heroku],
      [key: "Github Actions (coming soon!)", value: :github_actions, disabled: true],
      [key: "Travis CI", value: :travis_ci, disabled: true],
      [key: "Circle CI", value: :circle_ci, disabled: true],
      [key: "Semaphore CI", value: :semaphore_ci, disabled: true],
      [key: "Gitlab CI", value: :gitlab_ci, disabled: true],
      [key: "Jenkins", value: :jenkins, disabled: true]
    ]
  end
end

lib/ci_metrics_web/templates/repository/new.html.eex
<h1>Let's get you set up</h1>

<%= form_for @conn, Routes.repository_path(@conn, :create), fn f -> %>
  <fieldset>
    <label>
      Repository <%= text_input f, :repository_name, placeholder: "owner/repo" %>
    </label>

    <label>
      Personal access token <%= password_input f, :access_token %>
    </label>

    <label>
      Deployment Strategy <%= select f, :deployment_strategy, deployment_strategies(), prompt: "Please select one" %>
    </label>

    <%= submit "Create", class: "button button-outline" %>
  </fieldset>
<% end %>

lib/ci_metrics_web/templates/repository/show.html.eex
<h1>Repository: <%= full_name(@repository) %></h1>

<h3>Current Average Lead Time: <%= @repository.average_lead_time %></h3>

<canvas id="metrics-graph"></canvas>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script type="text/javascript">
  const ctx = document.getElementById('metrics-graph').getContext('2d');
  const chart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: <%= @repository.dates |> Jason.encode!() |> raw() %>,
          datasets: [{
              label: 'Lead Time',
              backgroundColor: '#C34182',
              borderColor: '#C34182',
              fill: true,
              data: <%= @repository.lead_times |> Jason.encode!() |> raw() %>
          }]
      },
      options: {
        scales: {
          xAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: 'Day'
            }
          }],
          yAxes: [{
            display: true,
            scaleLabel: {
              display: true,
              labelString: 'Hours'
            }
          }]
        }
      }
  });
</script>